import { scopedIdentity, scopedCreatePayload, scopedRotatePayload, scopedKeyActions } from './scoped-api-key-input.js';
const error=()=>{throw new Error('Respuesta segura de claves inválida');};
const text=(v:unknown):string=>typeof v==='string'?v:error();
const bool=(v:unknown):boolean=>typeof v==='boolean'?v:error();
const num=(v:unknown):number=>Number.isSafeInteger(v)&&(v as number)>=0?v as number:error();
const nullable=<T>(v:unknown,parse:(v:unknown)=>T):T|null=>v===null?null:parse(v);
const list=<T>(v:unknown,parse:(v:unknown)=>T):T[]=>Array.isArray(v)?v.map(parse):error();
function exact(v:any,keys:string[]){if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).sort().join()!==keys.sort().join())error();}
export function scopedMetadata(v:any){
 exact(v,['id','name','scope_version','scope_kind','billing_account_id','team','livemode','team_ids','action_ids','expires_at','manager_user_ids','status','created_at','revoked_at','revoke_at','replacement_key_id','last_used_at','can_manage','can_rotate','can_revoke']);
 if(!['scoped','legacy_unrestricted'].includes(v.scope_kind)||![null,2].includes(v.scope_version)||!['active','expired','revoked','scheduled_revocation','policy_invalid'].includes(v.status))error();
 return {id:scopedIdentity(v.id),name:nullable(v.name,text),scope_version:v.scope_version as 2|null,scope_kind:text(v.scope_kind),billing_account_id:scopedIdentity(v.billing_account_id),team:nullable(v.team,scopedIdentity),livemode:nullable(v.livemode,bool),team_ids:list(v.team_ids,scopedIdentity),action_ids:list(v.action_ids,text),expires_at:nullable(v.expires_at,num),manager_user_ids:list(v.manager_user_ids,scopedIdentity),status:text(v.status),created_at:nullable(v.created_at,num),revoked_at:nullable(v.revoked_at,num),revoke_at:nullable(v.revoke_at,num),replacement_key_id:nullable(v.replacement_key_id,scopedIdentity),last_used_at:nullable(v.last_used_at,num),can_manage:bool(v.can_manage),can_rotate:bool(v.can_rotate),can_revoke:bool(v.can_revoke)};
}
export function scopedCapabilities(v:any){exact(v,['can_create_scoped','can_emergency_revoke','is_billing_owner']);return {can_create_scoped:bool(v.can_create_scoped),can_emergency_revoke:bool(v.can_emergency_revoke),is_billing_owner:bool(v.is_billing_owner)};}
export function scopedList(v:any,account:string){exact(v,['items','next_cursor','capabilities']);return {items:list(v.items,x=>{const item=scopedMetadata(x);if(item.billing_account_id!==account)error();return item;}),next_cursor:nullable(v.next_cursor,text),capabilities:scopedCapabilities(v.capabilities)};}
export function scopedPolicy(v:any,account:string){exact(v,['billing_account_id','eligible_teams','actions','eligible_managers','max_expiry_days','max_overlap_seconds','can_create_scoped','can_emergency_revoke','is_billing_owner']);if(v.billing_account_id!==account||num(v.max_expiry_days)<1||v.max_expiry_days>365||num(v.max_overlap_seconds)>86400)error();return {billing_account_id:scopedIdentity(v.billing_account_id),eligible_teams:list(v.eligible_teams,(x:any)=>{exact(x,['id','name']);return{id:scopedIdentity(x.id),name:nullable(x.name,text)};}),actions:list(v.actions,(x:any)=>{exact(x,['id','label']);return{id:text(x.id),label:text(x.label)};}),eligible_managers:list(v.eligible_managers,(x:any)=>{exact(x,['uid','display_name']);return{uid:scopedIdentity(x.uid),display_name:nullable(x.display_name,text)};}),max_expiry_days:num(v.max_expiry_days),max_overlap_seconds:num(v.max_overlap_seconds),can_create_scoped:bool(v.can_create_scoped),can_emergency_revoke:bool(v.can_emergency_revoke),is_billing_owner:bool(v.is_billing_owner)};}
export function scopedAudit(v:any,key:string){exact(v,['items','next_cursor']);return {items:list(v.items,(x:any)=>{exact(x,['id','action','timestamp','actor_user_id','key_id','operation_id']);if(x.key_id!==key)error();return{id:text(x.id),action:text(x.action),timestamp:num(x.timestamp),actor_user_id:scopedIdentity(x.actor_user_id),key_id:scopedIdentity(x.key_id),operation_id:nullable(x.operation_id,text)};}),next_cursor:nullable(v.next_cursor,text)};}
export function scopedApprovalProjection(raw:any){
 if(!(scopedKeyActions as readonly string[]).includes(raw.action)){if(raw.scoped_key_change!=null||raw.receipt?.scoped_api_key!=null)error();return null;}
 const c=raw.scoped_key_change;exact(c,['name','livemode','billing_account_id','team_ids','action_ids','expires_at','manager_user_ids','action','previous_key_id','overlap_seconds','previous_revoke_at','unrelated_keys_affected','secret_disclosure']);
 const {action,previous_key_id,overlap_seconds,previous_revoke_at,unrelated_keys_affected,secret_disclosure,...scope}=c;
 const create=scopedCreatePayload(scope);const rotate=raw.action==='api_keys.rotate_scoped';
 if(action!==(rotate?'rotate':'create')||unrelated_keys_affected!==false||secret_disclosure!=='once'||raw.team!==null||raw.effect_scope!=='scoped_api_key'||raw.disclosure_version!=='scoped-api-key-v2'||raw.terms!==null||raw.billing_account_id!==create.billing_account_id||JSON.stringify(raw.requested_modes)!==JSON.stringify([create.livemode])||JSON.stringify(raw.existing_key_ids)!==JSON.stringify(rotate?[previous_key_id]:[]))error();
 if((!rotate&&(previous_key_id!==null||overlap_seconds!==0))||(rotate&&previous_key_id===null)||(raw.status==='pending'&&previous_revoke_at!==null))error();
 const payload=rotate?scopedRotatePayload(raw.payload):scopedCreatePayload(raw.payload);
 const change={...create,action,previous_key_id:nullable(previous_key_id,scopedIdentity),overlap_seconds:num(overlap_seconds),previous_revoke_at:nullable(previous_revoke_at,num),unrelated_keys_affected:false,secret_disclosure:'once'};
 if(rotate?(payload as any).key_id!==previous_key_id||(payload as any).overlap_seconds!==overlap_seconds:Object.entries(payload).some(([k,v])=>JSON.stringify((create as any)[k])!==JSON.stringify(v)))error();
 let receipt=null;
 if(raw.receipt){const r=raw.receipt.scoped_api_key;exact(r,['key_id','previous_key_id','overlap_seconds','previous_revoke_at','metadata']);const metadata=scopedMetadata(r.metadata);if(metadata.scope_version!==2||metadata.scope_kind!=='scoped'||metadata.name!==create.name||r.key_id===previous_key_id||raw.receipt.revoked_count!==(rotate&&overlap_seconds===0?1:0)||metadata.id!==r.key_id||metadata.billing_account_id!==create.billing_account_id||r.previous_key_id!==previous_key_id||r.overlap_seconds!==overlap_seconds||raw.receipt.keys?.length!==1||raw.receipt.keys[0].key_id!==r.key_id||raw.receipt.keys[0].type!=='api'||raw.receipt.keys[0].livemode!==create.livemode)error();for(const k of ['livemode','team_ids','action_ids','expires_at','manager_user_ids'])if(JSON.stringify((metadata as any)[k])!==JSON.stringify((create as any)[k]))error();receipt={key_id:scopedIdentity(r.key_id),previous_key_id:nullable(r.previous_key_id,scopedIdentity),overlap_seconds:num(r.overlap_seconds),previous_revoke_at:nullable(r.previous_revoke_at,num),metadata};}
 if((raw.status==='completed')!==!!receipt)error();
 return {change,receipt,payload};
}
